---
title: "Ujedi pasa u Njujorku u 2017. godini"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: united
---

```{r setup, include = FALSE}

# Ovde u takozvanom setup delu uvozite biblioteke, kreirate objekte, obradjujete i transformišete podatke. 

library (flexdashboard)
library (tidyverse)
library (plotly)

# Unos seta podataka

podacipsi2017 <- read_csv ("datadogs2017.csv")


# Ovo je obrata podataka koji će se koristiti za tekstualni deo a koji se odnosi na distrikte 

podacipsidistrikt <- podacipsi2017 %>%
  
  group_by (distrikt) %>%
  
  tally() %>%
  
  arrange (desc (n)) %>%
  
  mutate (perc = round ((n/sum(n)) * 100, 0))


#Kreiranje podskupa sa tri rase sa najvećim brojem ujeda za stubičasti grafikon 

podacipsirasa <- podacipsi2017 %>%
  
  group_by (rasa) %>%
  
  tally () %>%

  rename (Broj_ujeda= n) %>%
  
  arrange (desc (Broj_ujeda)) %>%
  
  top_n(3)

# Menjanje redosleda nivoa kako bi se oni ispravno prikazali na grafikonu

podacipsirasa$rasa <- factor (podacipsirasa$rasa,
                               levels = c ("Pit Bull", "Nepoznata", "Shih Tzu"))


#Objekat za pravljenje tabele

podacipsitabela <- podacipsi2017 %>%
  select (-poštanski_broj)


 


```

Row 
-----------------------------------------------------------------------
### **Koliko psi ujedaju u Njujorku** {data-height=350, align=justify}

Ovaj panel prikazuje osnovnu statistiku ujeda pasa u  Njujorku u 2017. godini. Podaci prikazuju da je bilo ukupno **`r nrow(podacipsi2017)`** ujeda. Stubičasti grafikon (bar chart) sa desne strane prikazuje koje tri rase pasa su najčešće ujedale. Iako možda postoji izvestan trend koji sugeriše da su **Pit bulovi** najagresivniji, možda je samo slučaj da ih ima znatno više nego drugih rasa pasa u Njujorku. **`r podacipsidistrikt[1,1]`** i **`r podacipsidistrikt[2,1]`** su dva distrikta sa najvećim procentom ujeda  **`r podacipsidistrikt[1,3]`%** i **`r podacipsidistrikt[2,3]`%**.



### **Tri rase pasa sa najvećim brojem ujeda u 2017. godini** 

```{r}
# Stubičasti grafikon za ujede prema rasi pasa uz pomoć biblioteka ggplot2 i plotly 

p <- ggplot (data = podacipsirasa, aes (x = rasa, y = Broj_ujeda))+
  
     geom_bar (stat = "identity", fill = c("darkred", "darkgreen", "darkblue")) +
  
     ylab ("Broj ujeda") +
  
     theme (legend.position = "none",
            
          panel.background = element_rect (fill = "lightcyan"))
  
# Postaju interaktivne uz pomoć funkcije ggplotly

p <- ggplotly (p)

p

```



Row 
-----------------------------------------------------------------------
### **Tabela ujeda pasa u Njujorku u 2017. godini** {data-height=650}

```{r}

# Koristimo DT paket kako bismo kreirali tabelu

DT :: datatable (podacipsitabela, options = list(
  bPaginate = TRUE))

```


